name: Test AWS Credentials

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Test AWS Access
        run: |
          aws sts get-caller-identity
          aws sagemaker list-training-jobs --max-results 1
